import { chmod, mkdir, rm, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

import type { Ctx, ShellCommand } from "../types.ts";
import {
  asInstalledBackend,
  bestEffortShell,
  bunBinary,
  checkedShell,
  checkoutRoot,
  logLineCount,
  type BackendFactoryOptions,
  type InstalledServiceBackend,
} from "./common.ts";

export const LAUNCHD_AGENT_LABEL = "herdr.collie";
export const AGENT_LABEL = LAUNCHD_AGENT_LABEL;

export interface LaunchdBackendOptions extends BackendFactoryOptions {
  /** Home directory used for the per-user LaunchAgent, injectable for fixture tests. */
  homeDir?: string;
  /** UID used to address launchd's per-user GUI domain, injectable for fixture tests. */
  uid?: string | number;
  /** Agent label, kept configurable for isolated integration fixtures. */
  label?: string;
}

interface ResolvedLaunchdOptions {
  rootDir: string;
  bun: string;
  homeDir: string;
  uid: string;
  label: string;
}

function resolvedOptions(options: LaunchdBackendOptions): ResolvedLaunchdOptions {
  const uid = options.uid ?? process.getuid?.() ?? process.env.UID ?? "0";
  return {
    rootDir: checkoutRoot(options.rootDir),
    bun: bunBinary(options.bun),
    homeDir: options.homeDir ?? homedir(),
    uid: String(uid),
    label: options.label ?? LAUNCHD_AGENT_LABEL,
  };
}

export function launchdDomain(options: LaunchdBackendOptions = {}): string {
  return `gui/${resolvedOptions(options).uid}`;
}

export function launchdTarget(options: LaunchdBackendOptions = {}): string {
  const resolved = resolvedOptions(options);
  return `${launchdDomain(options)}/${resolved.label}`;
}

export function launchdAgentFile(options: LaunchdBackendOptions = {}): string {
  const resolved = resolvedOptions(options);
  return join(resolved.homeDir, "Library", "LaunchAgents", `${resolved.label}.plist`);
}

function xmlEscape(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/** Render the per-user plist parallel to the old launchd agent generated by collie-ctl.sh. */
export function renderLaunchdPlist(ctx: Ctx, options: LaunchdBackendOptions = {}): string {
  const resolved = resolvedOptions(options);
  const rootDir = ctx.rootDir ?? resolved.rootDir;
  const logFile = join(ctx.stateDir, "collie.log");
  const env = [
    ["HERDR_PLUGIN_CONFIG_DIR", ctx.configDir],
    ["HERDR_PLUGIN_STATE_DIR", ctx.stateDir],
    ["HERDR_SOCKET_PATH", ctx.socketPath],
  ] as const;
  const environment = env
    .map(
      ([name, value]) =>
        `        <key>${name}</key>\n        <string>${xmlEscape(value)}</string>`,
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${xmlEscape(resolved.label)}</string>
    <key>ProgramArguments</key>
    <array>
        <string>${xmlEscape(resolved.bun)}</string>
        <string>scripts/ctl/main.ts</string>
        <string>exec-bridge</string>
    </array>
    <key>WorkingDirectory</key>
    <string>${xmlEscape(rootDir)}</string>
    <key>EnvironmentVariables</key>
    <dict>
${environment}
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
    <key>ThrottleInterval</key>
    <integer>5</integer>
    <key>StandardOutPath</key>
    <string>${xmlEscape(logFile)}</string>
    <key>StandardErrorPath</key>
    <string>${xmlEscape(logFile)}</string>
</dict>
</plist>
`;
}

export function createLaunchdBackend(options: LaunchdBackendOptions = {}): InstalledServiceBackend {
  const resolved = resolvedOptions(options);
  const agentFile = launchdAgentFile(options);
  const domain = `gui/${resolved.uid}`;
  const target = `${domain}/${resolved.label}`;

  return asInstalledBackend({
    async install(ctx: Ctx): Promise<void> {
      await mkdir(dirname(agentFile), { recursive: true });
      await writeFile(agentFile, renderLaunchdPlist(ctx, options), "utf8");
      // launchd rejects an agent plist that is left world-writable by an unusual umask.
      await chmod(agentFile, 0o644);
    },

    async start(ctx: Ctx): Promise<void> {
      // bootout makes start idempotent when an earlier install is still loaded.
      await bestEffortShell(ctx, "launchctl", ["bootout", target]);
      await bestEffortShell(ctx, "launchctl", ["enable", target]);
      await checkedShell(ctx, "launchctl", ["bootstrap", domain, agentFile]);
    },

    async stop(ctx: Ctx): Promise<void> {
      // Disable persists across logins; bootout stops the currently loaded agent.
      await bestEffortShell(ctx, "launchctl", ["disable", target]);
      await bestEffortShell(ctx, "launchctl", ["bootout", target]);
    },

    async uninstall(ctx: Ctx): Promise<void> {
      await rm(agentFile, { force: true });
      // Reset launchd's disabled bit so reinstalling the same label can run at login.
      await bestEffortShell(ctx, "launchctl", ["enable", target]);
    },

    async isActive(ctx: Ctx): Promise<boolean> {
      try {
        const result = await ctx.shell("launchctl", ["print", target]);
        if (result.exitCode !== 0) return false;
        return /(?:^|\n)\s*pid\s*=\s*\d+/i.test(result.stdout)
          || /(?:^|\n)\s*state\s*=\s*running/i.test(result.stdout);
      } catch {
        return false;
      }
    },

    logsCmd(_ctx: Ctx, lines?: number): ShellCommand {
      return {
        command: "tail",
        args: ["-n", String(logLineCount(lines)), join(_ctx.stateDir, "collie.log")],
      };
    },
  });
}

export const launchdBackend = createLaunchdBackend();
export const backend = launchdBackend;
export default launchdBackend;
